name: lint
on: [push, pull_request]
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install pnpm and install dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
         version: 5.18.9
         run_install: true

      - name: Run ESLint
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: '**/*.js'
